services:
  jetstream:
    image: ghcr.io/malpercio-dev/slipstream:${JETSTREAM_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: jetstream
    ports:
      - 6008:6008
    volumes:
      - ./data:/data
    environment:
      - JETSTREAM_DATA_DIR=/data
# livness check interval to restart when no events are received (default: 15sec)
      - JETSTREAM_LIVENESS_TTL=15s
